"""
Parser — reads Excel/CSV files and produces chunks for embedding.

TWO KINDS OF CHUNKING (this confuses everyone at first):

1. PANDAS CHUNKING (RAM management):
   "Read 1000 rows at a time so we don't run out of memory."
   This is about your SERVER not crashing. A 500k-row file is read in
   500 batches of 1000 rows. Memory stays flat at ~50MB.

2. RAG CHUNKING (semantic units):
   "Group 20 rows together as one chunk for embedding."
   This is about SEARCH QUALITY. Each chunk becomes one vector in ChromaDB.
   - Too small (1 row): the embedding is noisy, lacks context
   - Too large (500 rows): the embedding is too broad, matches everything vaguely
   - 20 rows: sweet spot for tabular data — specific enough to match,
     broad enough to have context

HOW THEY WORK TOGETHER:
   pandas reads 1000 rows into RAM
   → we split those 1000 rows into 50 chunks of 20 rows each
   → each chunk gets column headers prepended
   → chunks are sent to the embedder
   → pandas reads the NEXT 1000 rows
   → repeat until file is done

WHAT YOU'RE LEARNING:
- pandas chunked reading (chunksize parameter)
- Generator functions for memory-efficient data processing
- Why tabular data needs different chunking than regular text
- Sheet handling for multi-sheet Excel files
- Metadata attachment — what info travels with each chunk
"""

from pathlib import Path
from dataclasses import dataclass, field

import pandas as pd

from core.config import settings


@dataclass
class Chunk:
    """
    One chunk of data ready for embedding.

    WHY A DATACLASS:
    A dataclass is like a dictionary but with named fields and type checking.
    Instead of chunk["text"] (which could be misspelled as chunk["txet"] with
    no error), you get chunk.text (which your editor autocompletes and checks).

    WHY THESE FIELDS:
    - text: the actual content that gets embedded. Includes column headers +
      row data so the embedding model understands the meaning.
    - metadata: everything ChromaDB stores alongside the vector. This is how
      you filter search results later — "only search in sheet 'Q4 Sales'"
      or "only show results from rows 100-200."
    """

    text: str
    metadata: dict = field(default_factory=dict)

    # metadata looks like:
    # {
    #     "file_id": "abc123",
    #     "file_name": "sales_2024.xlsx",
    #     "sheet_name": "Q4",
    #     "row_start": 40,
    #     "row_end": 59,
    #     "column_names": "Name|Sales|Region|Date",
    #     "num_rows": 20,
    # }


def parse_file(file_path: Path, file_id: str) -> list[Chunk]:
    """
    Main entry point. Detects file type and delegates to the right parser.

    Args:
        file_path: Path to the uploaded file.
        file_id: Unique identifier for this file (used in metadata).
                 Generated by the upload endpoint so we can track which
                 chunks came from which file.

    Returns:
        List of Chunk objects ready for embedding.

    WHY NOT ASYNC:
    pandas is synchronous — it blocks while reading. In the pipeline (file 5),
    we'll run this in a thread pool using asyncio.to_thread() so it doesn't
    block the event loop. This is the standard pattern for wrapping synchronous
    libraries in async code.
    """
    suffix = file_path.suffix.lower()

    if suffix == ".csv":
        chunks = _parse_csv(file_path, file_id)
    elif suffix in (".xlsx", ".xls"):
        chunks = _parse_excel(file_path, file_id)
    else:
        raise ValueError(
            f"Unsupported file type: '{suffix}'. "
            f"Supported types: .csv, .xlsx, .xls"
        )

    summary = _build_summary_chunk(file_path, file_id, chunks)
    if summary:
        chunks.insert(0, summary)

    return chunks


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CSV parsing
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _parse_csv(file_path: Path, file_id: str) -> list[Chunk]:
    """
    Parse a CSV file using chunked reading.

    HOW pd.read_csv(chunksize=N) WORKS:
    Instead of returning a DataFrame, it returns an ITERATOR.
    Each iteration gives you a DataFrame with N rows.

        # Without chunksize — loads entire file into RAM:
        df = pd.read_csv("huge_file.csv")  # 500MB in memory!

        # With chunksize — reads N rows at a time:
        for batch in pd.read_csv("huge_file.csv", chunksize=1000):
            # batch is a DataFrame with 1000 rows
            # only ~5MB in memory at any time
            process(batch)

    This is a GENERATOR under the hood (same concept from llm.py).
    pandas yields one batch, you process it, pandas yields the next.
    The full file is never in memory.

    WHY WE READ HEADERS SEPARATELY:
    When using chunksize, each batch is an independent DataFrame that already
    has the column names. But we need the headers as a string to prepend to
    every chunk. So we extract them once from the first batch.
    """
    all_chunks = []
    row_offset = 0  # tracks absolute row position across batches
    headers = None

    reader = pd.read_csv(
        file_path,
        chunksize=settings.pandas_chunk_size,
        # dtype=str prevents pandas from guessing types.
        # Without this, "001" becomes 1, "2024-01-15" becomes a datetime,
        # and "N/A" becomes NaN. We want the raw string values because
        # that's what the user sees in their spreadsheet.
        dtype=str,
        # keep_default_na=False prevents pandas from converting strings
        # like "NA", "null", "None" into actual NaN values.
        keep_default_na=False,
    )

    for batch_df in reader:
        # Capture headers from the first batch
        if headers is None:
            headers = list(batch_df.columns)

        # Convert this pandas batch into RAG chunks
        batch_chunks = _dataframe_to_chunks(
            df=batch_df,
            headers=headers,
            file_id=file_id,
            file_name=file_path.name,
            sheet_name="default",  # CSVs don't have sheet names
            row_offset=row_offset,
        )

        all_chunks.extend(batch_chunks)
        row_offset += len(batch_df)

    return all_chunks


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Excel parsing
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _parse_excel(file_path: Path, file_id: str) -> list[Chunk]:
    """
    Parse an Excel file, handling multiple sheets.

    MULTI-SHEET HANDLING:
    An Excel file can have multiple sheets (tabs). Each sheet might contain
    completely different data — "Sales" in one sheet, "Employees" in another.
    We parse each sheet separately and tag chunks with the sheet name.
    This lets users ask "what are the sales figures?" and get results only
    from the Sales sheet, not the Employees sheet.

    WHY pd.ExcelFile:
    Opening an Excel file is expensive (it decompresses the .xlsx format).
    pd.ExcelFile opens it ONCE and lets us read multiple sheets from the
    same handle. Without it, reading 5 sheets would decompress the file 5 times.

    CHUNKED READING FOR EXCEL:
    Unlike CSV, pandas doesn't have a built-in chunksize for Excel.
    So we read sheet by sheet, and for very large sheets, we handle
    the chunking manually by slicing the DataFrame.
    """
    all_chunks = []

    # Open the Excel file once
    with pd.ExcelFile(file_path) as excel_file:
        sheet_names = excel_file.sheet_names

        for sheet_name in sheet_names:
            # Read the entire sheet with string types
            # For extremely large sheets (1M+ rows), you'd add manual
            # chunking here with nrows + skiprows. For sheets up to ~500k
            # rows this works fine — the RAM chunking is less critical
            # for Excel because the bottleneck is the decompression,
            # not the in-memory size.
            df = pd.read_excel(
                excel_file,
                sheet_name=sheet_name,
                dtype=str,
                keep_default_na=False,
            )

            # Skip empty sheets
            if df.empty:
                continue

            headers = list(df.columns)

            # For very large sheets, process in pandas-sized batches
            # to keep memory manageable
            for batch_start in range(0, len(df), settings.pandas_chunk_size):
                batch_end = min(batch_start + settings.pandas_chunk_size, len(df))
                batch_df = df.iloc[batch_start:batch_end]

                batch_chunks = _dataframe_to_chunks(
                    df=batch_df,
                    headers=headers,
                    file_id=file_id,
                    file_name=file_path.name,
                    sheet_name=sheet_name,
                    row_offset=batch_start,
                )

                all_chunks.extend(batch_chunks)

    return all_chunks


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# The core chunking logic — shared by CSV and Excel parsers
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _dataframe_to_chunks(
    df: pd.DataFrame,
    headers: list[str],
    file_id: str,
    file_name: str,
    sheet_name: str,
    row_offset: int,
) -> list[Chunk]:
    """
    Convert a DataFrame batch into RAG chunks with header prepending.

    THIS IS THE HEART OF THE PARSER. Here's what it does:

    Input DataFrame (20 rows of sales data):
        Name    | Sales | Region | Date
        John    | 5000  | South  | Jan 2024
        Sarah   | 7200  | North  | Jan 2024
        ...

    Output Chunk (text ready for embedding):
        "Columns: Name | Sales | Region | Date
         Row 1: John | 5000 | South | Jan 2024
         Row 2: Sarah | 7200 | North | Jan 2024
         ..."

    WHY PREPEND HEADERS:
    Without headers, the embedding model sees: "John, 5000, South, Jan 2024"
    It has NO IDEA what these values mean. Is 5000 a zip code? A salary? A price?

    With headers: "Columns: Name | Sales | Region | Date\nRow 1: John | 5000 | South"
    Now the model understands 5000 is a SALES figure and South is a REGION.
    The embedding vector captures this meaning, so searching "top sales by region"
    actually finds this chunk.

    WHY OVERLAP:
    chunk_overlap = 3 means the last 3 rows of chunk N repeat as the first 3
    rows of chunk N+1. This handles questions that span chunk boundaries:

        Chunk 1: rows 1-20   (rows 18,19,20 are the overlap)
        Chunk 2: rows 18-37  (rows 18,19,20 appear in BOTH chunks)
        Chunk 3: rows 35-54  (rows 35,36,37 appear in both chunks 2 and 3)

    If a user asks about row 19, it's found in both chunk 1 and chunk 2,
    giving the LLM more context to answer accurately.
    """
    chunks = []
    header_line = "Columns: " + " | ".join(headers)

    chunk_size = settings.chunk_size
    chunk_overlap = settings.chunk_overlap

    # Step size = how many NEW rows each chunk adds
    # With chunk_size=20 and overlap=3, step=17
    # Chunk 1: rows 0-19, Chunk 2: rows 17-36, Chunk 3: rows 34-53
    step = chunk_size - chunk_overlap

    total_rows = len(df)

    for start in range(0, total_rows, step):
        end = min(start + chunk_size, total_rows)
        chunk_df = df.iloc[start:end]

        # Skip tiny leftover chunks (less than overlap size)
        # These would just be duplicates of the previous chunk's overlap
        if len(chunk_df) < chunk_overlap and start > 0:
            break

        # Build the text representation of this chunk
        rows_text = _format_rows(chunk_df, headers, row_offset + start)
        chunk_text = f"{header_line}\n{rows_text}"

        # Calculate absolute row positions (what the user sees in Excel)
        # +2 because: +1 for 0-indexing, +1 for header row in the spreadsheet
        absolute_row_start = row_offset + start + 2
        absolute_row_end = row_offset + end + 1

        chunk = Chunk(
            text=chunk_text,
            metadata={
                "file_id": file_id,
                "file_name": file_name,
                "sheet_name": sheet_name,
                "row_start": absolute_row_start,
                "row_end": absolute_row_end,
                "column_names": " | ".join(headers),
                "num_rows": len(chunk_df),
            },
        )

        chunks.append(chunk)

        # If we've reached the end of the data, stop
        if end >= total_rows:
            break

    return chunks


def _format_rows(
    df: pd.DataFrame,
    headers: list[str],
    start_row: int,
) -> str:
    """
    Format DataFrame rows as readable text for embedding.

    Turns this DataFrame:
        Name    Sales   Region
        John    5000    South
        Sarah   7200    North

    Into this string:
        Row 2: John | 5000 | South
        Row 3: Sarah | 7200 | North

    WHY THIS FORMAT:
    - "Row N:" gives the LLM a way to cite specific rows in its answer
    - " | " separators are clear and unambiguous (commas can appear in data)
    - Each row on its own line helps the embedding model parse structure
    - Row numbers are ABSOLUTE (matching the spreadsheet) not relative to the chunk

    WHY WE USE str(val) FOR EACH VALUE:
    Even though we read with dtype=str, some edge cases (NaN, None) can
    slip through. str() is a safety net that ensures everything is a string.
    The .strip() removes leading/trailing whitespace from cell values.
    """
    lines = []

    for idx, (_, row) in enumerate(df.iterrows()):
        # +2: +1 for zero-indexing, +1 for header row in spreadsheet
        row_num = start_row + idx + 2
        values = " | ".join(str(val).strip() for val in row)
        lines.append(f"Row {row_num}: {values}")

    return "\n".join(lines)


def _build_summary_chunk(file_path: Path, file_id: str, chunks: list[Chunk]) -> Chunk | None:
    """
    Build a comprehensive summary chunk with pre-computed statistics
    so the LLM can answer aggregate questions (counts, distributions,
    averages) without needing to see every row.
    """
    if not chunks:
        return None

    suffix = file_path.suffix.lower()
    try:
        if suffix == ".csv":
            df = pd.read_csv(file_path, dtype=str, keep_default_na=False)
        else:
            df = pd.read_excel(file_path, dtype=str, keep_default_na=False)
    except Exception:
        return None

    total_rows = len(df)
    columns = list(df.columns)
    sheets = list(set(c.metadata.get("sheet_name", "default") for c in chunks))

    lines = [
        f"=== DATASET SUMMARY for {file_path.name} ===",
        f"Total rows: {total_rows}",
        f"Total columns: {len(columns)}",
        f"Column names: {' | '.join(columns)}",
        f"Sheets: {', '.join(sheets)}",
        "",
        "=== COLUMN STATISTICS (computed over ALL rows) ===",
    ]

    CATEGORICAL_THRESHOLD = 50

    for col in columns:
        unique_count = df[col].nunique()
        non_empty = df[col][df[col].str.strip() != ""].shape[0]
        lines.append(f"\n  Column: {col}")
        lines.append(f"    Non-empty values: {non_empty}/{total_rows}")
        lines.append(f"    Unique values: {unique_count}")

        if unique_count == 0:
            continue

        value_counts = df[col].value_counts()

        if unique_count <= CATEGORICAL_THRESHOLD:
            # Low cardinality: show ALL value counts — critical for aggregate queries
            counts_str = ", ".join(
                f"{val}={cnt}" for val, cnt in value_counts.items()
            )
            lines.append(f"    Value counts: {counts_str}")
        else:
            # High cardinality: show top 10 most common
            top = value_counts.head(10)
            counts_str = ", ".join(
                f"{val}={cnt}" for val, cnt in top.items()
            )
            lines.append(f"    Top 10 values: {counts_str}")

        # Try numeric stats if values look numeric
        try:
            numeric_col = pd.to_numeric(df[col], errors="coerce").dropna()
            if len(numeric_col) > total_rows * 0.5:
                lines.append(
                    f"    Numeric stats: min={numeric_col.min():.2f}, "
                    f"max={numeric_col.max():.2f}, "
                    f"mean={numeric_col.mean():.2f}, "
                    f"median={numeric_col.median():.2f}"
                )
        except Exception:
            pass

    # Add a few sample rows so the LLM understands the data format
    lines.append("\n=== SAMPLE ROWS (first 3) ===")
    header_line = "Columns: " + " | ".join(columns)
    lines.append(header_line)
    for idx, (_, row) in enumerate(df.head(3).iterrows()):
        values = " | ".join(str(val).strip() for val in row)
        lines.append(f"Row {idx + 2}: {values}")

    summary_text = "\n".join(lines)

    return Chunk(
        text=summary_text,
        metadata={
            "file_id": file_id,
            "file_name": file_path.name,
            "sheet_name": "summary",
            "row_start": 0,
            "row_end": total_rows,
            "column_names": " | ".join(columns),
            "num_rows": total_rows,
        },
    )